import './stripesConfig.mock';
import './stripesCore.mock';
import './stripes.mock';
import './intl.mock';
import './stripesIcon.mock';
import './stripesComponents.mock';
import './stripesSmartComponents.mock';
import './stripesUtils.mock';
import './stripesAcqComponents.mock';
