name: Centralized workflow test
on: [push, pull_request]

jobs:
  ui:
    uses: ncovercash/folio-github-actions/.github/workflows/ui.yml@stripes-904
    with:
      jest-enabled: true
      jest-test-command: yarn test --coverage
