name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@271a3c13366d7e8e8ac26fa3ba3b44516c813ad8
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push'
    secrets: inherit
    with:
      jest-enabled: true
      jest-test-command: yarn test --ci --color --coverage
