name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@31185b643750f3f285f57e419621a01b923e5b81
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push'
    secrets: inherit
    with:
      jest-enabled: true
      jest-test-command: yarn test --ci --color --coverage
