name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@v1
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      jest-enabled: true
      jest-test-command: yarn test --ci --color --coverage
